---
inherit_gem:
  eac_ruby_gem_support: ".rubocop.yml"
Rails/ApplicationRecord:
  Enabled: false
RSpec/MetadataStyle:
  Exclude:
  - spec/features/home_page_spec.rb
RSpec/Rails/InferredSpecType:
  Enabled: false
RSpec/SortMetadata:
  Exclude:
  - spec/features/home_page_spec.rb
Style/ExpandPathArguments:
  Exclude:
  - template/eac_rails_gem_support/rspec/appendable_rails_app/config.ru
Style/ExplicitBlockArgument:
  Exclude:
  - lib/eac_rails_gem_support/rspec/minitest_support.rb
Style/RedundantConstantBase:
  Exclude:
  - Gemfile
  - spec/rubocop_spec.rb
  - spec/spec_helper.rb
  - spec/support/rails_app_append/app/controllers/application_controller.rb
  - spec/support/rails_app_append/app/controllers/home_controller.rb
  - template/eac_rails_gem_support/rspec/appendable_rails_app/config/application.rb
  - template/eac_rails_gem_support/rspec/appendable_rails_app/config/routes.rb
  - template/eac_rails_gem_support/rspec/appendable_rails_app/config.ru
